### PR TITLE
Adds contextual parsing for OpenSCAD (scad)

### PR DESCRIPTION
**Pull request by atnbueno**

### CODE REVIEW

**Comment by atnbueno** [comment]
That didn't last long. OpenSCAD is not parsed with the just released 1.0.0 version.

**Comment by CoenraadS** [comment]
Sorry about that..

Is it just json file?

**Comment by atnbueno** [comment]
Unfortunately no. The only thing in common between JSON and OpenSCAD are the kind of comments. That was enough for your previous version which colorized everything but those comments. But now it seems that unless Prism is able to parse the language, nothing happens :-(

At least that's what I'm guessing after trying (in 1.0.1) this as a workaround:
```
switch (languageId) {
...
    case "scad":
        languageId = "json";
        break;
...
```

I have also tried other languages that are somewhat similar to OpenSCAD without success. But maybe I'm completely mistaken, because I've tried to map Visual Basic as "vb" (VSCode) to "vbnet" (Prism) also without success.

BTW, I have the original 200ms delay disabled but the new version takes **up to 8 seconds** to colorize my brackets.

**Comment by CoenraadS** [comment]
Sorry to hear that. Maybe there are faster language parsers out there I can use. Trying to do it myself was becoming an impossible task, although it was fast..

**Comment by atnbueno** [comment]
Thanks for fixing it in 1.0.2 👍 

OpenSCAD has a deeply nested syntax and your extension is a godsend for readability :-D

I can live with the speed (it's seems to be only the first pass). But you should probably remove the delay settings.

**Comment by CoenraadS** [comment]
Maybe there exists a tool to convert textmate languages to prism languages. Someone already put in a lot of work for the scad extension: https://github.com/efbenson/vscode-lang-scad/blob/master/syntaxes/scad.tmLanguage

**Comment by atnbueno** [comment]
Thanks for fixing it in 1.0.2 👍 

OpenSCAD has a deeply nested syntax and your extension is a godsend for readability :-D

Don't worry about the speed too much. It's only with the first file.

And yes, the proper fix would be a language definition for Prism, but the workaround is enough for now :-)

**Comment by CoenraadS** [comment]
ahaha our timing could not be worse, i just removed it again 💯

**Pull request merged**
