### PR TITLE
Fixes support for OpenSCAD and Visual Basic

### PR DESCRIPTION
**Pull request by atnbueno**
* OpenSCAD is not supported by Prism but it has the same kind of comments as JSON
* Visual Basic support was just a name matching problem, like JavaScript and TypeScript

### CODE REVIEW

**Comment by atnbueno** [comment]
Other languages not supported by [Prism](http://prismjs.com/) can be supported by this extension by finding a [Prism-supported language](http://prismjs.com/#languages-list) with the **same kind of comments**.

The old `settings.ts` file may help with that:
https://github.com/CoenraadS/BracketPair/blob/79f8a4a3e8d972d6e67b564785a37eec929f4e2b/src/settings.ts

**Comment by CoenraadS** [comment]
I'm moving files around still so I added this manually again. Hope it works!

**Comment by atnbueno** [comment]
It does! 👍

**Comment by atnbueno** [comment]
Mmmm. The JSON language definition in Prism has problems with /* comments, but if I map "scad" to "swift" everything works as expected. PR coming up! :-)

**Comment by atnbueno** [comment]
I tried a few _languageID_ (including "json5") and "swift" was the first that didn't do this:
Bracket problem

**Pull request closed without merging**
