### PR TITLE
Add ignoreFileExtensions setting

### PR DESCRIPTION
**Pull request by SeedyROM**
Adding the setting `bracketPairColorizer.ignoreFileExtensions` which allows users to specify which types of files they want to allow bracket pair colorization on.

This is default an empty array.

### CODE REVIEW

**Comment by SeedyROM** [comment]
GitHub glitched out on me, sorry for multiple closes and reopens!

This works under all the test conditions I've tried, please let me know if anybody else finds this useful.

**Comment by CoenraadS** [comment]
Thanks, I'll take a look at this during the weekend!

**Comment by SeedyROM** [comment]
Just checking in! Does everything seem alright?

**Comment by CoenraadS** [comment]
yes 👍 thanks!

**Comment by blimmer** [comment]
Excited to have this option! Thank you for implementing it. Could a release be issued?

**Comment by CoenraadS** [comment]
I just tried but the marketplace seems to be down at the moment.

**Comment by CoenraadS** [comment]
btw is there is a reason you prefer to ignore filename rather the an entire language?

**Comment by blimmer** [comment]
Is there an option exposed to ignore an entire language? That would definitely work for my use-case, too.

**Comment by CoenraadS** [comment]
Not in this project, I'm working on v2 which is why development is slowed on this project, because I would rather put new features into the new version and leave this one as 'stable'.

https://github.com/CoenraadS/Bracket-Pair-Colorizer-2

No eta until a public release though

**Pull request merged**
